services:
  - type: web
    name: Grid Guardian
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        from: MONGODB_URI
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://grid-guardian-api.onrender.com
