// LOCALHOST
###
GET http://localhost:8080/users

// LOCALHOST
###
GET http://localhost:8080/users/
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
###
GET http://localhost:8080/users/65f686bb683dbbdb77013770
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
###
POST http://localhost:8080/users
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N


{
   "username": "joel",
   "email": "joelcannon@mac.co",
   "password": "Abcxyz12!",
   "firstName": "Joel",
   "lastName": "Cannon",
   "phone": "+15412440897",
   "role": "admin"
}
###
POST http://localhost:8080/users
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N


{
   "username": "joelcannon",
   "email": "joelcannon@gmail.com",
   "password": "ABCxyz12!",
   "firstName": "Joel",
   "lastName": "Cannon",
   "phone": "+15412440896",
   "role": "tech"
}
###
DELETE http://localhost:8080/users/65f686bb683dbbdb77013770
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
###
PUT http://localhost:8080/users/65f686bb683dbbdb77013770
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

{
 
   "username": "joelC",
   "firstName": "Joel",
   "lastName": "Cannon",
   "phone": "+154124408",
   "role": "viewer"

}